//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Player
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sarki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sarki()
        {
            this.Sarki_Begenme = new HashSet<Sarki_Begenme>();
            this.Oynatma_Listesi = new HashSet<Oynatma_Listesi>();
        }
    
        public decimal sarki_id { get; set; }
        public string sanatci_ismi { get; set; }
        public string album_ismi { get; set; }
        public string sarki_ismi { get; set; }
        public Nullable<int> album_sirasi { get; set; }
        public Nullable<decimal> sarki_dakikasi { get; set; }
        public string sarki_hakkinda { get; set; }
        public string sarki_türü { get; set; }
        public string sarki_dosya_ismi { get; set; }
        public Nullable<decimal> kullanici_id { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sarki_Begenme> Sarki_Begenme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oynatma_Listesi> Oynatma_Listesi { get; set; }
    }
}
