//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Player
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sarki_Begenme
    {
        public Nullable<decimal> sarki_id { get; set; }
        public Nullable<decimal> kullanici_id { get; set; }
        public decimal sarki_begenme_id { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Sarki Sarki { get; set; }
    }
}
