//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Player
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takipci
    {
        public decimal takipci_id { get; set; }
        public decimal takip_eden_kullanici_id { get; set; }
        public decimal takip_edilen_kullanici_id { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
    }
}
